<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountryCurrencySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $countries= [
            'Afghanistan'          => ['currency' => 'Afghan Afghani', 'symbol' => '₾'],
            'Albania'              => ['currency' => 'Albanian Lek', 'symbol' => 'Lek'],
            'Algeria'              => ['currency' => 'Algerian Dinar', 'symbol' => 'د.ج'],
            'Andorra'              => ['currency' => 'Euro', 'symbol' => '€'],
            'Angola'               => ['currency' => 'Angolan Kwanza', 'symbol' => 'Kz'],
            'Antigua and Barbuda' => ['currency' => 'East Caribbean Dollar', 'symbol' => '$'],
            'Argentina'            => ['currency' => 'Argentine Peso', 'symbol' => '$'],
            'Armenia'              => ['currency' => 'Armenian Dram', 'symbol' => '֏'],
            'Australia'            => ['currency' => 'Australian Dollar', 'symbol' => 'A$'],
            'Austria'              => ['currency' => 'Euro', 'symbol' => '€'],
            'Azerbaijan'           => ['currency' => 'Azerbaijani Manat', 'symbol' => '₼'],
            'Bahamas'              => ['currency' => 'Bahamian Dollar', 'symbol' => '$'],
            'Bahrain'              => ['currency' => 'Bahraini Dinar', 'symbol' => 'ب.د'],
            'Bangladesh'           => ['currency' => 'Bangladeshi Taka', 'symbol' => '৳'],
            'Barbados'             => ['currency' => 'Barbadian Dollar', 'symbol' => '$'],
            'Belarus'              => ['currency' => 'Belarusian Ruble', 'symbol' => 'Br'],
            'Belgium'              => ['currency' => 'Euro', 'symbol' => '€'],
            'Belize'               => ['currency' => 'Belize Dollar', 'symbol' => '$'],
            'Benin'                => ['currency' => 'West African CFA Franc', 'symbol' => 'Fr'],
            'Bhutan'               => ['currency' => 'Bhutanese Ngultrum', 'symbol' => 'Nu.'],
            'Bolivia'              => ['currency' => 'Bolivian Boliviano', 'symbol' => 'Bs'],
            'Bosnia and Herzegovina'=> ['currency' => 'Bosnia and Herzegovina Convertible Mark', 'symbol' => 'KM'],
            'Botswana'             => ['currency' => 'Botswana Pula', 'symbol' => 'P'],
            'Brazil'               => ['currency' => 'Brazilian Real', 'symbol' => 'R$'],
            'Brunei'               => ['currency' => 'Brunei Dollar', 'symbol' => '$'],
            'Bulgaria'             => ['currency' => 'Bulgarian Lev', 'symbol' => 'лв'],
            'Burkina Faso'         => ['currency' => 'West African CFA Franc', 'symbol' => 'Fr'],
            'Burundi'              => ['currency' => 'Burundian Franc', 'symbol' => 'Fr'],
            'Cabo Verde'           => ['currency' => 'Cape Verdean Escudo', 'symbol' => 'Esc'],
            'Cambodia'             => ['currency' => 'Cambodian Riel', 'symbol' => '៛'],
            'Cameroon'             => ['currency' => 'Central African CFA Franc', 'symbol' => 'Fr'],
            'Canada'               => ['currency' => 'Canadian Dollar', 'symbol' => 'C$'],
            'Central African Republic' => ['currency' => 'Central African CFA Franc', 'symbol' => 'Fr'],
            'Chad'                 => ['currency' => 'Central African CFA Franc', 'symbol' => 'Fr'],
            'Chile'                => ['currency' => 'Chilean Peso', 'symbol' => '$'],
            'China'                => ['currency' => 'Chinese Yuan', 'symbol' => '¥'],
            'Colombia'             => ['currency' => 'Colombian Peso', 'symbol' => '$'],
            'Comoros'              => ['currency' => 'Comorian Franc', 'symbol' => 'Fr'],
            'Congo'                => ['currency' => 'Central African CFA Franc', 'symbol' => 'Fr'],
            'Costa Rica'           => ['currency' => 'Costa Rican Colón', 'symbol' => '₡'],
            'Croatia'              => ['currency' => 'Croatian Kuna', 'symbol' => 'kn'],
            'Cuba'                 => ['currency' => 'Cuban Peso', 'symbol' => '₱'],
            'Cyprus'               => ['currency' => 'Euro', 'symbol' => '€'],
            'Czech Republic'       => ['currency' => 'Czech Koruna', 'symbol' => 'Kč'],
            'Denmark'              => ['currency' => 'Danish Krone', 'symbol' => 'kr'],
            'Djibouti'             => ['currency' => 'Djiboutian Franc', 'symbol' => 'Fr'],
            'Dominica'             => ['currency' => 'East Caribbean Dollar', 'symbol' => '$'],
            'Dominican Republic'   => ['currency' => 'Dominican Peso', 'symbol' => '$'],
            'East Timor'           => ['currency' => 'US Dollar', 'symbol' => '$'],
            'Ecuador'              => ['currency' => 'US Dollar', 'symbol' => '$'],
            'Egypt'                => ['currency' => 'Egyptian Pound', 'symbol' => 'E£'],
            'El Salvador'          => ['currency' => 'US Dollar', 'symbol' => '$'],
            'Equatorial Guinea'    => ['currency' => 'Central African CFA Franc', 'symbol' => 'Fr'],
            'Eritrea'              => ['currency' => 'Eritrean Nakfa', 'symbol' => 'Nkf'],
            'Estonia'              => ['currency' => 'Euro', 'symbol' => '€'],
            'Eswatini'             => ['currency' => 'Swazi Lilangeni', 'symbol' => 'E'],
            'Ethiopia'             => ['currency' => 'Ethiopian Birr', 'symbol' => 'Br'],
            'Fiji'                 => ['currency' => 'Fijian Dollar', 'symbol' => 'FJ$'],
            'Finland'              => ['currency' => 'Euro', 'symbol' => '€'],
            'France'               => ['currency' => 'Euro', 'symbol' => '€'],
            'Gabon'                => ['currency' => 'Central African CFA Franc', 'symbol' => 'Fr'],
            'Gambia'               => ['currency' => 'Gambian Dalasi', 'symbol' => 'D'],
            'Georgia'              => ['currency' => 'Georgian Lari', 'symbol' => '₾'],
            'Germany'              => ['currency' => 'Euro', 'symbol' => '€'],
            'Ghana'                => ['currency' => 'Ghanaian Cedi', 'symbol' => '₵'],
            'Greece'               => ['currency' => 'Euro', 'symbol' => '€'],
            'Grenada'              => ['currency' => 'East Caribbean Dollar', 'symbol' => '$'],
            'Guatemala'            => ['currency' => 'Guatemalan Quetzal', 'symbol' => 'Q'],
            'Guinea'               => ['currency' => 'Guinean Franc', 'symbol' => 'Fr'],
            'Guinea-Bissau'        => ['currency' => 'West African CFA Franc', 'symbol' => 'Fr'],
            'Guyana'               => ['currency' => 'Guyanese Dollar', 'symbol' => '$'],
            'Haiti'                => ['currency' => 'Haitian Gourde', 'symbol' => 'G'],
            'Honduras'             => ['currency' => 'Honduran Lempira', 'symbol' => 'L'],
            'Hungary'              => ['currency' => 'Hungarian Forint', 'symbol' => 'Ft'],
            'Iceland'              => ['currency' => 'Icelandic Króna', 'symbol' => 'kr'],
            'India'                => ['currency' => 'Indian Rupee', 'symbol' => '₹'],
            'Indonesia'            => ['currency' => 'Indonesian Rupiah', 'symbol' => 'Rp'],
            'Iran'                 => ['currency' => 'Iranian Rial', 'symbol' => '﷼'],
            'Iraq'                 => ['currency' => 'Iraqi Dinar', 'symbol' => 'ع.د'],
            'Ireland'              => ['currency' => 'Euro', 'symbol' => '€'],
            'Israel'               => ['currency' => 'Israeli New Shekel', 'symbol' => '₪'],
            'Italy'                => ['currency' => 'Euro', 'symbol' => '€'],
            'Jamaica'              => ['currency' => 'Jamaican Dollar', 'symbol' => '$'],
            'Japan'                => ['currency' => 'Japanese Yen', 'symbol' => '¥'],
            'Jordan'               => ['currency' => 'Jordanian Dinar', 'symbol' => 'د.أ'],
            'Kazakhstan'           => ['currency' => 'Kazakhstani Tenge', 'symbol' => '₸'],
            'Kenya'                => ['currency' => 'Kenyan Shilling', 'symbol' => 'KSh'],
            'Kiribati'             => ['currency' => 'Australian Dollar', 'symbol' => 'A$'],
            'Korea, North'         => ['currency' => 'North Korean Won', 'symbol' => '₩'],
            'Korea, South'         => ['currency' => 'South Korean Won', 'symbol' => '₩'],
            'Kuwait'               => ['currency' => 'Kuwaiti Dinar', 'symbol' => 'د.ك'],
            'Kyrgyzstan'           => ['currency' => 'Kyrgystani Som', 'symbol' => 'с'],
            'Laos'                 => ['currency' => 'Lao Kip', 'symbol' => '₭'],
            'Latvia'               => ['currency' => 'Euro', 'symbol' => '€'],
            'Lebanon'              => ['currency' => 'Lebanese Pound', 'symbol' => 'ل.ل'],
            'Lesotho'              => ['currency' => 'Lesotho Loti', 'symbol' => 'L'],
            'Liberia'              => ['currency' => 'Liberian Dollar', 'symbol' => '$'],
            'Libya'                => ['currency' => 'Libyan Dinar', 'symbol' => 'د.ل'],
            'Liechtenstein'        => ['currency' => 'Swiss Franc', 'symbol' => 'CHF'],
            'Lithuania'            => ['currency' => 'Euro', 'symbol' => '€'],
            'Luxembourg'           => ['currency' => 'Euro', 'symbol' => '€'],
            'Madagascar'           => ['currency' => 'Malagasy Ariary', 'symbol' => 'Ar'],
            'Malawi'               => ['currency' => 'Malawian Kwacha', 'symbol' => 'MK'],
            'Malaysia'             => ['currency' => 'Malaysian Ringgit', 'symbol' => 'RM'],
            'Maldives'             => ['currency' => 'Maldivian Rufiyaa', 'symbol' => 'Rf'],
            'Mali'                 => ['currency' => 'West African CFA Franc', 'symbol' => 'Fr'],
            'Malta'                => ['currency' => 'Euro', 'symbol' => '€'],
            'Marshall Islands'     => ['currency' => 'US Dollar', 'symbol' => '$'],
            'Mauritania'           => ['currency' => 'Mauritanian Ouguiya', 'symbol' => 'UM'],
            'Mauritius'            => ['currency' => 'Mauritian Rupee', 'symbol' => '₨'],
            'Mexico'               => ['currency' => 'Mexican Peso', 'symbol' => '$'],
            'Micronesia'           => ['currency' => 'US Dollar', 'symbol' => '$'],
            'Moldova'              => ['currency' => 'Moldovan Leu', 'symbol' => 'L'],
            'Monaco'               => ['currency' => 'Euro', 'symbol' => '€'],
            'Mongolia'             => ['currency' => 'Mongolian Tugrik', 'symbol' => '₮'],
            'Montenegro'           => ['currency' => 'Euro', 'symbol' => '€'],
            'Morocco'              => ['currency' => 'Moroccan Dirham', 'symbol' => 'د.م.'],
            'Mozambique'           => ['currency' => 'Mozambican Metical', 'symbol' => 'MT'],
            'Myanmar'              => ['currency' => 'Burmese Kyat', 'symbol' => 'Ks'],
            'Namibia'              => ['currency' => 'Namibian Dollar', 'symbol' => 'N$'],
            'Nauru'                => ['currency' => 'Australian Dollar', 'symbol' => 'A$'],
            'Nepal'                => ['currency' => 'Nepalese Rupee', 'symbol' => 'Rs'],
            'Netherlands'          => ['currency' => 'Euro', 'symbol' => '€'],
            'New Zealand'          => ['currency' => 'New Zealand Dollar', 'symbol' => 'NZ$'],
            'Nicaragua'            => ['currency' => 'Nicaraguan Córdoba', 'symbol' => 'C$'],
            'Niger'                => ['currency' => 'West African CFA Franc', 'symbol' => 'Fr'],
            'Nigeria'              => ['currency' => 'Nigerian Naira', 'symbol' => '₦'],
            'North Macedonia'      => ['currency' => 'Macedonian Denar', 'symbol' => 'ден'],
            'Norway'               => ['currency' => 'Norwegian Krone', 'symbol' => 'kr'],
            'Oman'                 => ['currency' => 'Omani Rial', 'symbol' => 'ر.ع.'],
            'Pakistan'             => ['currency' => 'Pakistani Rupee', 'symbol' => 'Rs'],
            'Palau'                => ['currency' => 'US Dollar', 'symbol' => '$'],
            'Panama'               => ['currency' => 'Panamanian Balboa', 'symbol' => 'B/.'],
            'Papua New Guinea'     => ['currency' => 'Papua New Guinean Kina', 'symbol' => 'K'],
            'Paraguay'             => ['currency' => 'Paraguayan Guarani', 'symbol' => '₲'],
            'Peru'                 => ['currency' => 'Peruvian Sol', 'symbol' => 'S/'],
            'Philippines'          => ['currency' => 'Philippine Peso', 'symbol' => '₱'],
            'Poland'               => ['currency' => 'Polish Zloty', 'symbol' => 'zł'],
            'Portugal'             => ['currency' => 'Euro', 'symbol' => '€'],
            'Qatar'                => ['currency' => 'Qatari Rial', 'symbol' => 'ر.ق'],
            'Romania'              => ['currency' => 'Romanian Leu', 'symbol' => 'lei'],
            'Russia'               => ['currency' => 'Russian Ruble', 'symbol' => '₽'],
            'Rwanda'               => ['currency' => 'Rwandan Franc', 'symbol' => 'Fr'],
            'Saint Kitts and Nevis'=> ['currency' => 'East Caribbean Dollar', 'symbol' => '$'],
            'Saint Lucia'          => ['currency' => 'East Caribbean Dollar', 'symbol' => '$'],
            'Saint Vincent and the Grenadines'=> ['currency' => 'East Caribbean Dollar', 'symbol' => '$'],
            'Samoa'                => ['currency' => 'Samoan Tala', 'symbol' => 'SAT'],
            'San Marino'           => ['currency' => 'Euro', 'symbol' => '€'],
            'Sao Tome and Principe'=> ['currency' => 'São Tomé and Príncipe Dobra', 'symbol' => 'Db'],
            'Saudi Arabia'         => ['currency' => 'Saudi Riyal', 'symbol' => 'ر.س'],
            'Senegal'              => ['currency' => 'West African CFA Franc', 'symbol' => 'Fr'],
            'Serbia'               => ['currency' => 'Serbian Dinar', 'symbol' => 'дин.'],
            'Seychelles'           => ['currency' => 'Seychellois Rupee', 'symbol' => '₨'],
            'Sierra Leone'         => ['currency' => 'Sierra Leonean Leone', 'symbol' => 'Le'],
            'Singapore'            => ['currency' => 'Singapore Dollar', 'symbol' => 'S$'],
            'Slovakia'             => ['currency' => 'Euro', 'symbol' => '€'],
            'Slovenia'             => ['currency' => 'Euro', 'symbol' => '€'],
            'Solomon Islands'      => ['currency' => 'Solomon Islands Dollar', 'symbol' => 'SI$'],
            'Somalia'              => ['currency' => 'Somali Shilling', 'symbol' => 'Sh'],
            'South Africa'         => ['currency' => 'South African Rand', 'symbol' => 'R'],
            'South Sudan'          => ['currency' => 'South Sudanese Pound', 'symbol' => '£'],
            'Spain'                => ['currency' => 'Euro', 'symbol' => '€'],
            'Sri Lanka'            => ['currency' => 'Sri Lankan Rupee', 'symbol' => 'Rs'],
            'Sudan'                => ['currency' => 'Sudanese Pound', 'symbol' => 'ج.س.'],
            'Suriname'             => ['currency' => 'Surinamese Dollar', 'symbol' => '$'],
            'Sweden'               => ['currency' => 'Swedish Krona', 'symbol' => 'kr'],
            'Switzerland'          => ['currency' => 'Swiss Franc', 'symbol' => 'CHF'],
            'Syria'                => ['currency' => 'Syrian Pound', 'symbol' => 'ل.س'],
            'Taiwan'               => ['currency' => 'New Taiwan Dollar', 'symbol' => 'NT$'],
            'Tajikistan'           => ['currency' => 'Tajikistani Somoni', 'symbol' => 'SM'],
            'Tanzania'             => ['currency' => 'Tanzanian Shilling', 'symbol' => 'TSh'],
            'Thailand'             => ['currency' => 'Thai Baht', 'symbol' => '฿'],
            'Togo'                 => ['currency' => 'West African CFA Franc', 'symbol' => 'Fr'],
            'Tonga'                => ['currency' => 'Tongan Paʻanga', 'symbol' => 'T$'],
            'Trinidad and Tobago'  => ['currency' => 'Trinidad and Tobago Dollar', 'symbol' => '$'],
            'Tunisia'              => ['currency' => 'Tunisian Dinar', 'symbol' => 'د.ت'],
            'Turkey'               => ['currency' => 'Turkish Lira', 'symbol' => '₺'],
            'Turkmenistan'         => ['currency' => 'Turkmenistani Manat', 'symbol' => 'T'],
            'Tuvalu'               => ['currency' => 'Australian Dollar', 'symbol' => 'A$'],
            'Uganda'               => ['currency' => 'Ugandan Shilling', 'symbol' => 'USh'],
            'Ukraine'              => ['currency' => 'Ukrainian Hryvnia', 'symbol' => '₴'],
            'United Arab Emirates' => ['currency' => 'United Arab Emirates Dirham', 'symbol' => 'د.إ'],
            'United Kingdom'       => ['currency' => 'Pound Sterling', 'symbol' => '£'],
            'United States'        => ['currency' => 'US Dollar', 'symbol' => '$'],
            'Uruguay'              => ['currency' => 'Uruguayan Peso', 'symbol' => '$'],
            'Uzbekistan'           => ['currency' => 'Uzbekistani Som', 'symbol' => 'лв'],
            'Vanuatu'              => ['currency' => 'Vanuatu Vatu', 'symbol' => 'VT'],
            'Vatican City'         => ['currency' => 'Euro', 'symbol' => '€'],
            'Venezuela'            => ['currency' => 'Venezuelan Bolívar', 'symbol' => 'Bs'],
            'Vietnam'              => ['currency' => 'Vietnamese Dong', 'symbol' => '₫'],
            'Yemen'                => ['currency' => 'Yemeni Rial', 'symbol' => 'ر.ي'],
            'Zambia'               => ['currency' => 'Zambian Kwacha', 'symbol' => 'ZK'],
            'Zimbabwe'             => ['currency' => 'Zimbabwean Dollar', 'symbol' => 'Z$'],
        ];

        foreach ($countries as $name => $data) {
            Country::where('name', $name)
                ->update([
                    'currency' => $data['currency'],
                    'symbol' => $data['symbol']
                ]);
        }
    }
}
